@startuml deplomentView1


agent pixlrServer
node MobileDevice [
Mobile device
----
Frontend
]

cloud Server [
Cloud provider
   
Cloud provided Server service
&
Microservices
&
Cloud Storage solution
]

node DevelopmentEnvironment [
Development Environment
----
react native, node.js
]

MobileDevice -up- Server
DevelopmentEnvironment -- Server
pixlrServer - Server

@enduml


