@startuml Upload image
    title Upload image
    
    actor User
    participant "Image API" as I
    participant "Image Processing" as IP
    database "Cloud Storage" as FS

    User ->  I: Upload Image
    I -> IP: Initiate processing
    IP -> FS: Store processed image
    FS -> User: Confirm storage
@enduml
