@startuml ImageControllerComponents

skinparam linetype ortho

package "Image Controller" {

    class RequestHandlerAndTaskManager {
        + validateRequests()
        + parseParameters()
        + routeRequests()
        + manageProcessingWorkflow()
    }


    class MonitoringAndLogging {
        + logActivity()
        + trackPerformanceMetrics()
        + alertAdministrators()
    }


    class ConfigurationManager {
        + manageProcessingSettings()
        + manageAPIIntegrations()
        + handleOperationalParameters()
    }

    class APIInterface {
        + translateToAPIResponses()
        + handleIncomingRequests()
    }

    ' Connections
    RequestHandlerAndTaskManager -- MonitoringAndLogging 
    RequestHandlerAndTaskManager -- ConfigurationManager 
    RequestHandlerAndTaskManager -- APIInterface 
}

@enduml