@startuml
top to bottom direction

package "Image Sharing App" {
    [Mobile App] as MobileApp
    [Image API] as ImageAPI
    [Pixlr API] as PixlrAPI
    [Cloud Storage API] as CloudStorageAPI
    [Notification API] as NotificationAPI
    [User API] as UserAPI
}

package "External Systems" {
    [User Devices] as UserDevices
    [Pixlr Service] as PixlrService
    [Cloud Storage Service] as CloudStorageService
    [Firebase Cloud Messaging] as NotificationService
}

UserDevices -- UserAPI : User Interaction/Authentication
UserAPI -- MobileApp : User Interaction
MobileApp -- ImageAPI : Images Upload/Download
MobileApp -- NotificationAPI : Manage Notifications

ImageAPI -- PixlrAPI : Edit Image
ImageAPI -- CloudStorageAPI : Save/Retrieve Images
PixlrAPI -- PixlrService : External Editing Service
CloudStorageAPI -- CloudStorageService : Store/Retrieve Image/Data
NotificationAPI -- NotificationService : Push Notifications

@enduml